version: '3'

services:
  web:
    image: nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./data/www:/data/www
      - ./nginx:/etc/nginx
      - ./logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    command: /bin/bash -c "nginx -g 'daemon off;'"
